//! Enchantment persistence + Java codegen.
//!
//! Uses the generic `registry` table (asset_type = "enchantment") so we
//! avoid yet another schema migration. The legacy EnchantmentEditor's
//! local Enchantment type maps cleanly onto the metadata blob.
//!
//! The generator emits a `net.minecraft.world.item.enchantment.Enchantment`
//! subclass with:
//!   * Rarity from `weight` (>=10 common, >=5 uncommon, >=2 rare, else very_rare)
//!   * EnchantmentCategory from `applies_to` (BREAKABLE / WEAPON / ARMOR /
//!     ARMOR_HEAD / DIGGER / BOW / FISHING_ROD / CROSSBOW / WEARABLE)
//!   * `getMaxLevel`, `getMinCost`, `getMaxCost`, `isTreasureOnly`,
//!     `isCurse`, `canEnchant` overrides driven by the editor flags.

use serde::Deserialize;
use tauri::State;

use crate::commands::codegen_commands::GeneratedFile;
use super::project_commands::DbState;

#[derive(Debug, Default, Deserialize)]
struct EnchantmentMeta {
    #[serde(default)]
    name: String,
    #[serde(default)]
    display_name: String,
    #[serde(default)]
    description: String,
    #[serde(default = "default_max_level")]
    max_level: i32,
    #[serde(default)]
    is_treasure: bool,
    #[serde(default)]
    is_curse: bool,
    #[serde(default = "default_anvil_merge")]
    can_anvil_merge: bool,
    #[serde(default = "default_anvil_cost")]
    anvil_cost: i32,
    #[serde(default = "default_weight")]
    weight: i32,
    #[serde(default = "default_applies_to")]
    applies_to: String,
}

fn default_max_level() -> i32 { 3 }
fn default_anvil_merge() -> bool { true }
fn default_anvil_cost() -> i32 { 4 }
fn default_weight() -> i32 { 10 }
fn default_applies_to() -> String { "BREAKABLE".into() }

const VALID_CATEGORIES: &[&str] = &[
    "BREAKABLE", "WEAPON", "ARMOR", "ARMOR_FEET", "ARMOR_LEGS", "ARMOR_CHEST",
    "ARMOR_HEAD", "DIGGER", "BOW", "FISHING_ROD", "TRIDENT", "WEARABLE",
    "CROSSBOW", "VANISHABLE",
];

fn java_package(namespace: &str, sub: &str) -> String {
    let base = if namespace.contains('.') {
        namespace.to_string()
    } else {
        format!("com.modstudio.{}", namespace)
    };
    format!("{}.{}", base, sub)
}

fn pascal(s: &str) -> String {
    s.split(|c: char| !c.is_alphanumeric())
        .filter(|p| !p.is_empty())
        .map(|p| {
            let mut chars = p.chars();
            match chars.next() {
                None => String::new(),
                Some(c) => c.to_uppercase().collect::<String>() + chars.as_str(),
            }
        })
        .collect()
}

fn rarity_for_weight(w: i32) -> &'static str {
    if w >= 10 { "COMMON" }
    else if w >= 5 { "UNCOMMON" }
    else if w >= 2 { "RARE" }
    else { "VERY_RARE" }
}

#[tauri::command]
pub async fn generate_enchantment_class(
    db: State<'_, DbState>,
    asset_id: i64,
) -> Result<GeneratedFile, String> {
    let asset = db
        .0
        .get_asset(asset_id)
        .map_err(|e| format!("get_asset: {}", e))?
        .ok_or_else(|| format!("Asset {} not found", asset_id))?;

    if asset.asset_type != "enchantment" {
        return Err(format!("Asset {} is not an enchantment", asset_id));
    }

    let meta: EnchantmentMeta = asset
        .metadata
        .as_deref()
        .map(serde_json::from_str)
        .transpose()
        .map_err(|e| format!("Could not parse enchantment metadata: {}", e))?
        .unwrap_or_default();

    if meta.max_level < 1 || meta.max_level > 10 {
        return Err(format!(
            "Enchantment max_level must be 1..=10, got {}",
            meta.max_level
        ));
    }
    let cat = meta.applies_to.to_uppercase();
    if !VALID_CATEGORIES.contains(&cat.as_str()) {
        return Err(format!(
            "Enchantment applies_to '{}' is not a known EnchantmentCategory",
            meta.applies_to
        ));
    }
    if meta.weight < 1 || meta.weight > 10 {
        return Err(format!(
            "Enchantment weight must be 1..=10, got {}",
            meta.weight
        ));
    }

    let class_name = pascal(&asset.asset_name);
    let pkg = java_package(&asset.namespace, "enchantment");
    let rarity = rarity_for_weight(meta.weight);

    let display = if meta.display_name.is_empty() {
        asset.asset_name.clone()
    } else {
        meta.display_name.clone()
    };

    let body = format!(
        "// =============================================================================\n\
         //  Generated by Minecraft Mod Studio — Enchantment\n\
         //  asset_id={asset_id} · max_level={max_lvl} · weight={weight} · rarity={rarity}\n\
         // =============================================================================\n\n\
         package {pkg};\n\n\
         import net.minecraft.world.entity.EquipmentSlot;\n\
         import net.minecraft.world.item.enchantment.Enchantment;\n\
         import net.minecraft.world.item.enchantment.EnchantmentCategory;\n\n\
         /**\n\
         \x20* {display}\n\
         {desc}\
         \x20*/\n\
         public final class {class} extends Enchantment {{\n\
         \x20   public {class}() {{\n\
         \x20       super(Rarity.{rarity}, EnchantmentCategory.{cat}, ALL_ARMOR_SLOTS);\n\
         \x20   }}\n\n\
         \x20   private static final EquipmentSlot[] ALL_ARMOR_SLOTS = new EquipmentSlot[] {{\n\
         \x20       EquipmentSlot.HEAD, EquipmentSlot.CHEST, EquipmentSlot.LEGS, EquipmentSlot.FEET\n\
         \x20   }};\n\n\
         \x20   @Override public int getMaxLevel() {{ return {max_lvl}; }}\n\n\
         \x20   @Override public int getMinCost(int level) {{ return 1 + (level - 1) * 8; }}\n\
         \x20   @Override public int getMaxCost(int level) {{ return getMinCost(level) + {anvil_cost}; }}\n\n\
         \x20   @Override public boolean isTreasureOnly() {{ return {treasure}; }}\n\
         \x20   @Override public boolean isCurse() {{ return {curse}; }}\n\
         \x20   @Override protected boolean checkCompatibility(Enchantment other) {{\n\
         \x20       return super.checkCompatibility(other);\n\
         \x20   }}\n\
         {anvil_merge}\
         }}\n",
        asset_id = asset_id,
        max_lvl = meta.max_level,
        weight = meta.weight,
        rarity = rarity,
        pkg = pkg,
        display = display,
        desc = if meta.description.is_empty() {
            String::new()
        } else {
            format!(" * {}\n", meta.description.replace('\n', "\n * "))
        },
        class = class_name,
        cat = cat,
        anvil_cost = meta.anvil_cost.max(0),
        treasure = meta.is_treasure,
        curse = meta.is_curse,
        anvil_merge = if !meta.can_anvil_merge {
            "\n    @Override public boolean canEnchant(net.minecraft.world.item.ItemStack stack) {\n        return false; // disabled in editor\n    }\n".to_string()
        } else {
            String::new()
        },
    );

    Ok(GeneratedFile {
        file_name: format!("{}.java", class_name),
        package_path: pkg.replace('.', "/"),
        source: body,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn rarity_buckets() {
        assert_eq!(rarity_for_weight(10), "COMMON");
        assert_eq!(rarity_for_weight(5), "UNCOMMON");
        assert_eq!(rarity_for_weight(2), "RARE");
        assert_eq!(rarity_for_weight(1), "VERY_RARE");
    }

    #[test]
    fn defaults_are_sane() {
        let m: EnchantmentMeta = serde_json::from_str("{}").unwrap();
        assert_eq!(m.max_level, 3);
        assert_eq!(m.weight, 10);
        assert_eq!(m.applies_to, "BREAKABLE");
        assert!(m.can_anvil_merge);
    }

    #[test]
    fn full_payload_parses() {
        let m: EnchantmentMeta = serde_json::from_str(
            r#"{"name":"piercing","display_name":"Piercing","max_level":5,"is_treasure":true,"weight":3,"applies_to":"WEAPON","anvil_cost":6}"#,
        )
        .unwrap();
        assert_eq!(m.max_level, 5);
        assert!(m.is_treasure);
        assert_eq!(m.weight, 3);
        assert_eq!(m.applies_to, "WEAPON");
    }
}
