//! Item-variant codegen — Tool / Armor / Food.
//!
//! Tools, armor pieces and foods are all *items* in Minecraft, just with
//! different superclasses and constructors. We already have a `items`
//! table; rather than introduce three new tables, the user picks an
//! existing item and a variant kind, plus a few extra parameters
//! (tier, slot, nutrition…), and the generator emits the specialised
//! Java class. The plain `generate_item_class` command stays available
//! for "I just want a vanilla Item".
//!
//! These three commands move Tool / Armor / Food from Skeleton to
//! Partial in the Feature Catalog: they take a real DB-backed Item as
//! input and produce a compileable starter, but they intentionally
//! leave material-class wiring, slot registration, and tag handling
//! as TODOs since those involve extra files (tags, datapacks) that
//! belong in their own future PRs.

use serde::Deserialize;
use tauri::State;

use crate::commands::codegen_commands::GeneratedFile;
use super::project_commands::DbState;

#[derive(Debug, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ToolKind {
    Pickaxe,
    Axe,
    Shovel,
    Hoe,
    Sword,
}

impl ToolKind {
    fn java_class(&self) -> &'static str {
        match self {
            ToolKind::Pickaxe => "PickaxeItem",
            ToolKind::Axe => "AxeItem",
            ToolKind::Shovel => "ShovelItem",
            ToolKind::Hoe => "HoeItem",
            ToolKind::Sword => "SwordItem",
        }
    }
    fn import(&self) -> &'static str {
        match self {
            ToolKind::Pickaxe => "import net.minecraft.world.item.PickaxeItem;",
            ToolKind::Axe => "import net.minecraft.world.item.AxeItem;",
            ToolKind::Shovel => "import net.minecraft.world.item.ShovelItem;",
            ToolKind::Hoe => "import net.minecraft.world.item.HoeItem;",
            ToolKind::Sword => "import net.minecraft.world.item.SwordItem;",
        }
    }
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ArmorSlot {
    Head,
    Chest,
    Legs,
    Feet,
}

impl ArmorSlot {
    fn java(&self) -> &'static str {
        match self {
            ArmorSlot::Head => "Type.HELMET",
            ArmorSlot::Chest => "Type.CHESTPLATE",
            ArmorSlot::Legs => "Type.LEGGINGS",
            ArmorSlot::Feet => "Type.BOOTS",
        }
    }
    fn name(&self) -> &'static str {
        match self {
            ArmorSlot::Head => "helmet",
            ArmorSlot::Chest => "chestplate",
            ArmorSlot::Legs => "leggings",
            ArmorSlot::Feet => "boots",
        }
    }
}

fn java_package(namespace: &str, sub: &str) -> String {
    let base = if namespace.contains('.') {
        namespace.to_string()
    } else {
        format!("com.modstudio.{}", namespace)
    };
    format!("{}.{}", base, sub)
}

fn pascal(s: &str) -> String {
    s.split(|c: char| !c.is_alphanumeric())
        .filter(|p| !p.is_empty())
        .map(|p| {
            let mut chars = p.chars();
            match chars.next() {
                None => String::new(),
                Some(c) => c.to_uppercase().collect::<String>() + chars.as_str(),
            }
        })
        .collect()
}

// ============================================================================
// Tool
// ============================================================================

#[tauri::command]
pub async fn generate_tool_class(
    db: State<'_, DbState>,
    item_id: i64,
    kind: ToolKind,
    tier: String,        // WOOD / STONE / IRON / GOLD / DIAMOND / NETHERITE
    attack_damage_bonus: f64,
    attack_speed_modifier: f64,
) -> Result<GeneratedFile, String> {
    let item = db
        .0
        .get_item(item_id)
        .map_err(|e| format!("get_item: {}", e))?
        .ok_or_else(|| format!("Item {} not found", item_id))?;

    let tier_upper = tier.to_uppercase();
    if !["WOOD", "STONE", "IRON", "GOLD", "DIAMOND", "NETHERITE"].contains(&tier_upper.as_str()) {
        return Err(format!(
            "Tool tier '{}' must be one of WOOD/STONE/IRON/GOLD/DIAMOND/NETHERITE",
            tier
        ));
    }
    if attack_speed_modifier > 0.0 {
        return Err("attack_speed_modifier should be negative or 0 (Minecraft convention)".into());
    }

    let class_name = pascal(&item.item_name);
    let pkg = java_package(&item.namespace, "item");
    let java_class = kind.java_class();
    let import = kind.import();

    let body = format!(
        "// =============================================================================\n\
         //  Generated by Minecraft Mod Studio — Tool variant of item id={item_id}\n\
         //  kind={kind:?} · tier={tier_upper} · +damage={dmg} · speed_mod={spd}\n\
         // =============================================================================\n\n\
         package {pkg};\n\n\
         {import}\n\
         import net.minecraft.world.item.Item;\n\
         import net.minecraft.world.item.Tiers;\n\n\
         /**\n\
         \x20* {display_name} ({kind_name}).\n\
         \x20*\n\
         \x20* TODO:\n\
         \x20*   - Replace `Tiers.{tier_upper}` with a custom Tier if you need\n\
         \x20*     different mining level / durability / enchantability.\n\
         \x20*   - Add this item to the matching tag (e.g. #minecraft:mineable/{kind_lower}).\n\
         \x20*/\n\
         public final class {class} extends {java_class} {{\n\
         \x20   public {class}() {{\n\
         \x20       super(Tiers.{tier_upper}, {dmg_int}, {spd}f, new Item.Properties());\n\
         \x20   }}\n\
         }}\n",
        item_id = item_id,
        kind = kind,
        tier_upper = tier_upper,
        pkg = pkg,
        import = import,
        display_name = item.display_name,
        kind_name = format!("{:?}", kind),
        kind_lower = format!("{:?}", kind).to_lowercase(),
        class = class_name,
        java_class = java_class,
        dmg = attack_damage_bonus,
        dmg_int = attack_damage_bonus as i32,
        spd = attack_speed_modifier,
    );

    Ok(GeneratedFile {
        file_name: format!("{}.java", class_name),
        package_path: pkg.replace('.', "/"),
        source: body,
    })
}

// ============================================================================
// Armor
// ============================================================================

#[tauri::command]
pub async fn generate_armor_class(
    db: State<'_, DbState>,
    item_id: i64,
    slot: ArmorSlot,
    armor_material_const: String, // e.g. "ArmorMaterials.IRON" or "MyArmorMaterial.RUBY"
) -> Result<GeneratedFile, String> {
    let item = db
        .0
        .get_item(item_id)
        .map_err(|e| format!("get_item: {}", e))?
        .ok_or_else(|| format!("Item {} not found", item_id))?;

    if armor_material_const.trim().is_empty() {
        return Err("armor_material_const cannot be empty".into());
    }

    let slot_name = slot.name();
    let class_name = format!("{}{}", pascal(&item.item_name), pascal(slot_name));
    let pkg = java_package(&item.namespace, "item");

    let body = format!(
        "// =============================================================================\n\
         //  Generated by Minecraft Mod Studio — Armor variant of item id={item_id}\n\
         //  slot={slot_name} · material={mat}\n\
         // =============================================================================\n\n\
         package {pkg};\n\n\
         import net.minecraft.world.item.ArmorItem;\n\
         import net.minecraft.world.item.ArmorItem.Type;\n\
         import net.minecraft.world.item.ArmorMaterial;\n\
         import net.minecraft.world.item.Item;\n\n\
         /**\n\
         \x20* {display_name} ({slot_name}).\n\
         \x20*\n\
         \x20* TODO:\n\
         \x20*   - Replace `{mat}` with the real ArmorMaterial reference.\n\
         \x20*   - Provide a layer texture at\n\
         \x20*     assets/<modid>/textures/models/armor/<material>_layer_1.png.\n\
         \x20*/\n\
         public final class {class} extends ArmorItem {{\n\
         \x20   public {class}() {{\n\
         \x20       super(({mat}), {slot_java}, new Item.Properties());\n\
         \x20   }}\n\
         }}\n",
        item_id = item_id,
        slot_name = slot_name,
        mat = armor_material_const,
        pkg = pkg,
        display_name = item.display_name,
        class = class_name,
        slot_java = slot.java(),
    );

    Ok(GeneratedFile {
        file_name: format!("{}.java", class_name),
        package_path: pkg.replace('.', "/"),
        source: body,
    })
}

// ============================================================================
// Food
// ============================================================================

#[tauri::command]
pub async fn generate_food_class(
    db: State<'_, DbState>,
    item_id: i64,
    nutrition: i32,
    saturation_modifier: f64,
    always_eat: bool,
    can_eat_when_full: bool,
) -> Result<GeneratedFile, String> {
    let item = db
        .0
        .get_item(item_id)
        .map_err(|e| format!("get_item: {}", e))?
        .ok_or_else(|| format!("Item {} not found", item_id))?;

    if nutrition < 0 || nutrition > 20 {
        return Err(format!("Food nutrition must be 0..=20, got {}", nutrition));
    }
    if saturation_modifier < 0.0 {
        return Err("Food saturation_modifier must be >= 0".into());
    }

    let class_name = pascal(&item.item_name);
    let pkg = java_package(&item.namespace, "item");

    let mut food_builder = String::from("new FoodProperties.Builder()\n");
    food_builder.push_str(&format!("            .nutrition({})\n", nutrition));
    food_builder.push_str(&format!(
        "            .saturationMod({}f)\n",
        saturation_modifier
    ));
    if always_eat {
        food_builder.push_str("            .alwaysEat()\n");
    }
    if can_eat_when_full {
        food_builder.push_str("            .fast()\n");
    }
    food_builder.push_str("            .build()");

    let body = format!(
        "// =============================================================================\n\
         //  Generated by Minecraft Mod Studio — Food variant of item id={item_id}\n\
         //  nutrition={nutrition} · saturation={sat} · always_eat={always}\n\
         // =============================================================================\n\n\
         package {pkg};\n\n\
         import net.minecraft.world.food.FoodProperties;\n\
         import net.minecraft.world.item.Item;\n\n\
         /**\n\
         \x20* {display_name} (food).\n\
         \x20*\n\
         \x20* TODO:\n\
         \x20*   - Add MobEffectInstance entries via .effect(...) for status effects.\n\
         \x20*   - Adjust `eatAnimation` if needed.\n\
         \x20*/\n\
         public final class {class} {{\n\
         \x20   public static final FoodProperties FOOD = {food};\n\n\
         \x20   public static Item.Properties properties() {{\n\
         \x20       return new Item.Properties().food(FOOD);\n\
         \x20   }}\n\n\
         \x20   private {class}() {{}}\n\
         }}\n",
        item_id = item_id,
        nutrition = nutrition,
        sat = saturation_modifier,
        always = always_eat,
        pkg = pkg,
        display_name = item.display_name,
        class = class_name,
        food = food_builder,
    );

    Ok(GeneratedFile {
        file_name: format!("{}.java", class_name),
        package_path: pkg.replace('.', "/"),
        source: body,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn tool_kind_class_names() {
        assert_eq!(ToolKind::Pickaxe.java_class(), "PickaxeItem");
        assert_eq!(ToolKind::Sword.java_class(), "SwordItem");
    }

    #[test]
    fn armor_slot_constants() {
        assert_eq!(ArmorSlot::Head.java(), "Type.HELMET");
        assert_eq!(ArmorSlot::Chest.name(), "chestplate");
    }
}
