//! Item-variant codegen — Tool / Armor / Food.
//!
//! All three variants are *items* in Minecraft, just with different
//! superclasses and constructors. The user picks an existing item,
//! optionally overrides a few fields, and the generator emits the
//! specialised Java class.
//!
//! As of PR #26 these generators are **version-aware** (consult
//! `feature_system::version_matrix`) and **extras-aware** (read
//! the persisted `Item` columns added in PR #24 — `tool_kind`,
//! `tool_tier`, `armor_material`, `armor_slot`, `food_eat_seconds`
//! etc.). That means the user can persist all the rules once via
//! the Item editor and call these commands with just `item_id`,
//! or supply per-call overrides for one-off generation.

use serde::{Deserialize, Serialize};
use tauri::State;

use crate::commands::codegen_commands::GeneratedFile;
use crate::feature_system::version_matrix::{profile_for, LoaderId, VersionProfile};
use super::project_commands::DbState;

#[derive(Debug, Clone, Copy, Deserialize, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum ToolKind {
    Pickaxe,
    Axe,
    Shovel,
    Hoe,
    Sword,
}

impl ToolKind {
    fn java_class(&self) -> &'static str {
        match self {
            ToolKind::Pickaxe => "PickaxeItem",
            ToolKind::Axe => "AxeItem",
            ToolKind::Shovel => "ShovelItem",
            ToolKind::Hoe => "HoeItem",
            ToolKind::Sword => "SwordItem",
        }
    }
    fn import(&self) -> &'static str {
        match self {
            ToolKind::Pickaxe => "import net.minecraft.world.item.PickaxeItem;",
            ToolKind::Axe => "import net.minecraft.world.item.AxeItem;",
            ToolKind::Shovel => "import net.minecraft.world.item.ShovelItem;",
            ToolKind::Hoe => "import net.minecraft.world.item.HoeItem;",
            ToolKind::Sword => "import net.minecraft.world.item.SwordItem;",
        }
    }
    fn from_str(s: &str) -> Option<ToolKind> {
        match s.trim().to_ascii_lowercase().as_str() {
            "pickaxe" => Some(ToolKind::Pickaxe),
            "axe" => Some(ToolKind::Axe),
            "shovel" => Some(ToolKind::Shovel),
            "hoe" => Some(ToolKind::Hoe),
            "sword" => Some(ToolKind::Sword),
            _ => None,
        }
    }
    fn slug(&self) -> &'static str {
        match self {
            ToolKind::Pickaxe => "pickaxe",
            ToolKind::Axe => "axe",
            ToolKind::Shovel => "shovel",
            ToolKind::Hoe => "hoe",
            ToolKind::Sword => "sword",
        }
    }
}

#[derive(Debug, Clone, Copy, Deserialize, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum ArmorSlot {
    Head,
    Chest,
    Legs,
    Feet,
}

impl ArmorSlot {
    fn java(&self) -> &'static str {
        match self {
            ArmorSlot::Head => "Type.HELMET",
            ArmorSlot::Chest => "Type.CHESTPLATE",
            ArmorSlot::Legs => "Type.LEGGINGS",
            ArmorSlot::Feet => "Type.BOOTS",
        }
    }
    fn name(&self) -> &'static str {
        match self {
            ArmorSlot::Head => "helmet",
            ArmorSlot::Chest => "chestplate",
            ArmorSlot::Legs => "leggings",
            ArmorSlot::Feet => "boots",
        }
    }
    fn from_str(s: &str) -> Option<ArmorSlot> {
        match s.trim().to_ascii_lowercase().as_str() {
            "head" | "helmet" => Some(ArmorSlot::Head),
            "chest" | "chestplate" => Some(ArmorSlot::Chest),
            "legs" | "leggings" => Some(ArmorSlot::Legs),
            "feet" | "boots" => Some(ArmorSlot::Feet),
            _ => None,
        }
    }
}

const VALID_TIERS: [&str; 6] = ["WOOD", "STONE", "IRON", "GOLD", "DIAMOND", "NETHERITE"];

fn java_package(namespace: &str, sub: &str) -> String {
    let base = if namespace.contains('.') {
        namespace.to_string()
    } else {
        format!("com.modstudio.{}", namespace)
    };
    format!("{}.{}", base, sub)
}

fn pascal(s: &str) -> String {
    s.split(|c: char| !c.is_alphanumeric())
        .filter(|p| !p.is_empty())
        .map(|p| {
            let mut chars = p.chars();
            match chars.next() {
                None => String::new(),
                Some(c) => c.to_uppercase().collect::<String>() + chars.as_str(),
            }
        })
        .collect()
}

/// Build the `// Generated by …` header for a variant Java class.
/// Mirrors the format used by Block / Item / Recipe generators so the
/// user can see at a glance which (mc_version, loader) the file targets.
fn variant_header(variant: &str, item_id: i64, profile: &VersionProfile) -> String {
    format!(
        "// =============================================================================\n\
         //  Generated by Minecraft Mod Studio — {variant} variant of item id={item_id}\n\
         //  Target: {ver} · loader: {loader:?} · pack_format: {pf} · java: {jv}\n\
         // =============================================================================\n\n",
        variant = variant,
        item_id = item_id,
        ver = profile.mc_version,
        loader = profile.loader,
        pf = profile.pack_format,
        jv = profile.java_version,
    )
}

/// Pick the right `Item.Properties` chain start for the loader.
/// Forge / NeoForge use `new Item.Properties()`; Fabric uses
/// `new Item.Settings()` — but both are aliased internally to
/// `Item.Properties` from 1.20.5+. To keep the variant generators
/// loader-portable we always emit the modern `Item.Properties()`
/// since vanilla item variants (Sword/Pickaxe/Armor/...) take an
/// `Item.Properties` arg on every supported version.
fn properties_init(_profile: &VersionProfile) -> &'static str {
    "new Item.Properties()"
}

// ============================================================================
// Tool
// ============================================================================

/// Tool generation parameters. Every field is optional: when omitted,
/// the value is read from the persisted Item row (the `tool_kind` /
/// `tool_tier` columns added in PR #24).
#[derive(Debug, Default, Deserialize)]
pub struct ToolOverrides {
    pub kind: Option<ToolKind>,
    pub tier: Option<String>,
    pub attack_damage_bonus: Option<f64>,
    pub attack_speed_modifier: Option<f64>,
}

#[tauri::command]
pub async fn generate_tool_class(
    db: State<'_, DbState>,
    item_id: i64,
    // Legacy fields (kept for backwards compatibility — the React
    // editor prior to PR #26 sent these explicitly).
    kind: Option<ToolKind>,
    tier: Option<String>,
    attack_damage_bonus: Option<f64>,
    attack_speed_modifier: Option<f64>,
    // New: structured overrides blob. If both are sent, the explicit
    // fields above take precedence.
    overrides: Option<ToolOverrides>,
) -> Result<GeneratedFile, String> {
    let item = db
        .0
        .get_item(item_id)
        .map_err(|e| format!("get_item: {}", e))?
        .ok_or_else(|| format!("Item {} not found", item_id))?;
    let project = db
        .0
        .get_project(item.project_id)
        .map_err(|e| format!("get_project: {}", e))?
        .ok_or_else(|| format!("Project {} not found", item.project_id))?;
    let profile = profile_for(&project.minecraft_version, &project.mod_loader);

    let ovr = overrides.unwrap_or_default();

    // Resolve tool kind: explicit arg → overrides → DB extras.
    let kind = kind
        .or(ovr.kind)
        .or_else(|| item.tool_kind.as_deref().and_then(ToolKind::from_str))
        .ok_or_else(|| {
            format!(
                "Tool kind not specified and Item {} has no tool_kind persisted. \
                 Pass `kind` explicitly or set Tool kind in the Item editor.",
                item_id
            )
        })?;

    // Resolve tier: explicit arg → overrides → DB extras → default IRON.
    let tier_raw = tier
        .or(ovr.tier)
        .or_else(|| item.tool_tier.clone())
        .unwrap_or_else(|| "IRON".into());
    let tier_upper = tier_raw.to_uppercase();
    if !VALID_TIERS.contains(&tier_upper.as_str()) {
        return Err(format!(
            "Tool tier '{}' must be one of {}",
            tier_raw,
            VALID_TIERS.join("/")
        ));
    }

    let attack_damage = attack_damage_bonus
        .or(ovr.attack_damage_bonus)
        .or(item.attack_damage)
        .unwrap_or(3.0);
    let attack_speed = attack_speed_modifier
        .or(ovr.attack_speed_modifier)
        .unwrap_or(-2.4);
    if attack_speed > 0.0 {
        return Err("attack_speed_modifier should be negative or 0 (Minecraft convention)".into());
    }

    let class_name = pascal(&item.item_name);
    let pkg = java_package(&item.namespace, "item");
    let java_class = kind.java_class();
    let import = kind.import();
    let header = variant_header("Tool", item_id, &profile);
    let props_init = properties_init(&profile);
    let extra_props = build_item_props_chain(&item, &profile);

    let body = format!(
        "{header}\
         package {pkg};\n\n\
         {import}\n\
         import net.minecraft.world.item.Item;\n\
         import net.minecraft.world.item.Tiers;\n\n\
         /**\n\
         \x20* {display_name} ({kind_slug}, tier {tier}).\n\
         \x20*\n\
         \x20* Persisted fields used: tool_kind={tk:?} tool_tier={tt:?}\n\
         \x20* attack_damage={dmg} attack_speed={spd}\n\
         \x20*\n\
         \x20* TODO:\n\
         \x20*   - Replace `Tiers.{tier}` with a custom Tier if you need\n\
         \x20*     different mining level / durability / enchantability.\n\
         \x20*   - Add this item to the matching tag\n\
         \x20*     (e.g. #minecraft:mineable/{kind_slug}).\n\
         \x20*/\n\
         public final class {class} extends {java_class} {{\n\
         \x20   public {class}() {{\n\
         \x20       super(Tiers.{tier}, {dmg_int}, {spd}f, {props}{extra});\n\
         \x20   }}\n\
         }}\n",
        header = header,
        pkg = pkg,
        import = import,
        display_name = item.display_name,
        kind_slug = kind.slug(),
        tier = tier_upper,
        tk = item.tool_kind,
        tt = item.tool_tier,
        dmg = attack_damage,
        spd = attack_speed,
        class = class_name,
        java_class = java_class,
        dmg_int = attack_damage as i32,
        props = props_init,
        extra = extra_props,
    );

    Ok(GeneratedFile {
        file_name: format!("{}.java", class_name),
        package_path: pkg.replace('.', "/"),
        source: body,
    })
}

// ============================================================================
// Armor
// ============================================================================

#[derive(Debug, Default, Deserialize)]
pub struct ArmorOverrides {
    pub slot: Option<ArmorSlot>,
    pub armor_material_const: Option<String>,
}

#[tauri::command]
pub async fn generate_armor_class(
    db: State<'_, DbState>,
    item_id: i64,
    slot: Option<ArmorSlot>,
    armor_material_const: Option<String>,
    overrides: Option<ArmorOverrides>,
) -> Result<GeneratedFile, String> {
    let item = db
        .0
        .get_item(item_id)
        .map_err(|e| format!("get_item: {}", e))?
        .ok_or_else(|| format!("Item {} not found", item_id))?;
    let project = db
        .0
        .get_project(item.project_id)
        .map_err(|e| format!("get_project: {}", e))?
        .ok_or_else(|| format!("Project {} not found", item.project_id))?;
    let profile = profile_for(&project.minecraft_version, &project.mod_loader);

    let ovr = overrides.unwrap_or_default();

    let slot = slot
        .or(ovr.slot)
        .or_else(|| item.armor_slot.as_deref().and_then(ArmorSlot::from_str))
        .ok_or_else(|| {
            format!(
                "Armor slot not specified and Item {} has no armor_slot persisted.",
                item_id
            )
        })?;

    let material = armor_material_const
        .or(ovr.armor_material_const)
        .or_else(|| item.armor_material.clone())
        .unwrap_or_else(|| "ArmorMaterials.IRON".into());
    if material.trim().is_empty() {
        return Err("armor_material_const cannot be empty".into());
    }

    let slot_name = slot.name();
    let class_name = format!("{}{}", pascal(&item.item_name), pascal(slot_name));
    let pkg = java_package(&item.namespace, "item");
    let header = variant_header("Armor", item_id, &profile);
    let props_init = properties_init(&profile);
    let extra_props = build_item_props_chain(&item, &profile);

    let body = format!(
        "{header}\
         package {pkg};\n\n\
         import net.minecraft.world.item.ArmorItem;\n\
         import net.minecraft.world.item.ArmorItem.Type;\n\
         import net.minecraft.world.item.ArmorMaterial;\n\
         import net.minecraft.world.item.Item;\n\n\
         /**\n\
         \x20* {display_name} ({slot_name}).\n\
         \x20*\n\
         \x20* Persisted fields used: armor_material={mat_persist:?} armor_slot={slot_persist:?}\n\
         \x20* armor_defense={def:?} armor_toughness={tough:?} knockback_resistance={kbr:?}\n\
         \x20*\n\
         \x20* TODO:\n\
         \x20*   - Replace `{mat}` with the real ArmorMaterial reference.\n\
         \x20*   - Provide a layer texture at\n\
         \x20*     assets/<modid>/textures/models/armor/<material>_layer_1.png.\n\
         \x20*   - Implement defense / toughness / knockback_resistance via the\n\
         \x20*     ArmorMaterial; the values above are stored on the Item row\n\
         \x20*     for reference but vanilla reads them from the material.\n\
         \x20*/\n\
         public final class {class} extends ArmorItem {{\n\
         \x20   public {class}() {{\n\
         \x20       super(({mat}), {slot_java}, {props}{extra});\n\
         \x20   }}\n\
         }}\n",
        header = header,
        pkg = pkg,
        display_name = item.display_name,
        slot_name = slot_name,
        mat_persist = item.armor_material,
        slot_persist = item.armor_slot,
        def = item.armor_defense,
        tough = item.armor_toughness,
        kbr = item.knockback_resistance,
        mat = material,
        class = class_name,
        slot_java = slot.java(),
        props = props_init,
        extra = extra_props,
    );

    Ok(GeneratedFile {
        file_name: format!("{}.java", class_name),
        package_path: pkg.replace('.', "/"),
        source: body,
    })
}

// ============================================================================
// Food
// ============================================================================

#[derive(Debug, Default, Deserialize)]
pub struct FoodOverrides {
    pub nutrition: Option<i32>,
    pub saturation_modifier: Option<f64>,
    pub always_eat: Option<bool>,
    pub can_eat_when_full: Option<bool>,
    pub eat_seconds: Option<f64>,
}

#[tauri::command]
pub async fn generate_food_class(
    db: State<'_, DbState>,
    item_id: i64,
    nutrition: Option<i32>,
    saturation_modifier: Option<f64>,
    always_eat: Option<bool>,
    can_eat_when_full: Option<bool>,
    overrides: Option<FoodOverrides>,
) -> Result<GeneratedFile, String> {
    let item = db
        .0
        .get_item(item_id)
        .map_err(|e| format!("get_item: {}", e))?
        .ok_or_else(|| format!("Item {} not found", item_id))?;
    let project = db
        .0
        .get_project(item.project_id)
        .map_err(|e| format!("get_project: {}", e))?
        .ok_or_else(|| format!("Project {} not found", item.project_id))?;
    let profile = profile_for(&project.minecraft_version, &project.mod_loader);

    let ovr = overrides.unwrap_or_default();

    let nutrition = nutrition.or(ovr.nutrition).unwrap_or(4);
    let saturation_modifier = saturation_modifier
        .or(ovr.saturation_modifier)
        .unwrap_or(0.3);
    let always_eat = always_eat
        .or(ovr.always_eat)
        .unwrap_or(item.food_always_eat);
    let can_eat_when_full = can_eat_when_full
        .or(ovr.can_eat_when_full)
        .unwrap_or(item.food_eat_fast);

    if !(0..=20).contains(&nutrition) {
        return Err(format!("Food nutrition must be 0..=20, got {}", nutrition));
    }
    if saturation_modifier < 0.0 {
        return Err("Food saturation_modifier must be >= 0".into());
    }

    let eat_seconds = ovr.eat_seconds.or(item.food_eat_seconds);

    let class_name = pascal(&item.item_name);
    let pkg = java_package(&item.namespace, "item");
    let header = variant_header("Food", item_id, &profile);

    let mut food_builder = String::from("new FoodProperties.Builder()\n");
    food_builder.push_str(&format!("            .nutrition({})\n", nutrition));
    food_builder.push_str(&format!(
        "            .saturationMod({}f)\n",
        saturation_modifier
    ));
    if always_eat {
        food_builder.push_str("            .alwaysEat()\n");
    }
    if can_eat_when_full {
        food_builder.push_str("            .fast()\n");
    }
    if let Some(secs) = eat_seconds {
        food_builder.push_str(&format!(
            "            // TODO 1.20.5+: .eatSeconds({}f) — only available on newer versions\n",
            secs
        ));
    }

    // Optional MobEffect lines pulled from food_effects_json. We never
    // fail the generation if this is malformed — drop a TODO comment
    // instead so the user can see what was ignored.
    let mut effect_block = String::new();
    if let Some(json) = item.food_effects_json.as_deref().filter(|s| !s.is_empty()) {
        match serde_json::from_str::<Vec<FoodEffectSpec>>(json) {
            Ok(effects) if !effects.is_empty() => {
                effect_block.push_str(
                    "            // Effects parsed from item.food_effects_json:\n",
                );
                for e in effects {
                    effect_block.push_str(&format!(
                        "            // .effect(() -> new MobEffectInstance(MobEffects.{effect}, {dur}, {amp}), {prob}f)\n",
                        effect = e.effect.to_uppercase().replace('-', "_"),
                        dur = e.duration_ticks,
                        amp = e.amplifier,
                        prob = e.probability,
                    ));
                }
            }
            _ => {
                effect_block.push_str(
                    "            // TODO: food_effects_json on the Item row could not be parsed — \n            // expected a JSON array of {effect, duration_ticks, amplifier, probability}.\n",
                );
            }
        }
    }
    food_builder.push_str(&effect_block);
    food_builder.push_str("            .build()");

    let extra_props = build_item_props_chain(&item, &profile);

    let body = format!(
        "{header}\
         package {pkg};\n\n\
         import net.minecraft.world.food.FoodProperties;\n\
         import net.minecraft.world.item.Item;\n\n\
         /**\n\
         \x20* {display_name} (food).\n\
         \x20*\n\
         \x20* Persisted fields used: food_eat_seconds={secs:?} food_always_eat={ae}\n\
         \x20* food_eat_fast={ef} food_effects_json={effects:?}\n\
         \x20*\n\
         \x20* TODO:\n\
         \x20*   - Uncomment the .effect(...) lines below if MobEffects are needed.\n\
         \x20*/\n\
         public final class {class} {{\n\
         \x20   public static final FoodProperties FOOD = {food};\n\n\
         \x20   public static Item.Properties properties() {{\n\
         \x20       return new Item.Properties().food(FOOD){extra};\n\
         \x20   }}\n\n\
         \x20   private {class}() {{}}\n\
         }}\n",
        header = header,
        pkg = pkg,
        display_name = item.display_name,
        secs = item.food_eat_seconds,
        ae = item.food_always_eat,
        ef = item.food_eat_fast,
        effects = item.food_effects_json,
        class = class_name,
        food = food_builder,
        extra = extra_props,
    );

    Ok(GeneratedFile {
        file_name: format!("{}.java", class_name),
        package_path: pkg.replace('.', "/"),
        source: body,
    })
}

#[derive(Debug, Deserialize)]
struct FoodEffectSpec {
    effect: String,
    #[serde(default)]
    duration_ticks: i32,
    #[serde(default)]
    amplifier: i32,
    #[serde(default = "default_probability")]
    probability: f64,
}

fn default_probability() -> f64 {
    1.0
}

// ============================================================================
// Shared: build the Item.Properties chain from extras
// ============================================================================
//
// Both the variant generators above and the plain `generate_item_class`
// command (PR #26 update in `codegen_commands.rs`) call this to append
// the rules persisted in PR #24 to an `Item.Properties()` expression.
//
// Returned string is a chain like
//   .stacksTo(16).rarity(Rarity.RARE).fireResistant().craftRemainder(Items.BUCKET)
// (or empty if no extras apply).
//
// Version-aware: `.attributes(...)` and `.eatSeconds(...)` are only
// appended on profiles that support them.

pub(crate) fn build_item_props_chain(
    item: &crate::db::operations::Item,
    profile: &VersionProfile,
) -> String {
    let mut out = String::new();

    // stacksTo / maxCount on Forge / NeoForge; on Fabric the Settings
    // builder uses .maxCount() but that's also the same name from 1.20.5.
    // We special-case Fabric callers in the variant code (they pass
    // Item.Settings); for Forge variants we use the standard name.
    if item.max_stack_size != 64 {
        if matches!(profile.loader, LoaderId::Fabric) {
            out.push_str(&format!(".maxCount({})", item.max_stack_size));
        } else {
            out.push_str(&format!(".stacksTo({})", item.max_stack_size));
        }
    }

    let rarity = item.rarity.to_uppercase();
    if rarity != "COMMON" && !rarity.is_empty() {
        out.push_str(&format!(".rarity(Rarity.{})", rarity));
    }

    if let Some(d) = item.durability {
        if d > 0 {
            out.push_str(&format!(".durability({})", d));
        }
    }

    if item.is_fire_resistant {
        out.push_str(".fireResistant()");
    }

    // craftRemainder = the bucket-style "leaves a thing in the grid" item.
    if let Some(rem) = item.recipe_remainder.as_deref().filter(|s| !s.is_empty()) {
        out.push_str(&format!(".craftRemainder({})", rem));
    }

    // 1.20.5+ added .attributes(...) for item-attached attribute modifiers.
    // On older profiles we leave a TODO comment instead of emitting
    // something that won't compile.
    if profile.has_item_attributes_setter {
        if let Some(_attr_json) = item
            .attribute_modifiers_json
            .as_deref()
            .filter(|s| !s.is_empty())
        {
            out.push_str(
                "/* TODO: .attributes(ItemAttributeModifiers.builder().add(...).build()) */",
            );
        }
    }

    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::db::operations::Item;

    fn sample_item() -> Item {
        Item {
            id: Some(1),
            project_id: 1,
            item_name: "ruby".into(),
            display_name: "Ruby".into(),
            namespace: "rubymod".into(),
            ..Item::default()
        }
    }

    fn forge_1_20_4() -> VersionProfile {
        profile_for("1.20.4", "forge")
    }

    fn neoforge_1_21() -> VersionProfile {
        profile_for("1.21", "neoforge")
    }

    fn fabric_1_20_4() -> VersionProfile {
        profile_for("1.20.4", "fabric")
    }

    #[test]
    fn tool_kind_class_names() {
        assert_eq!(ToolKind::Pickaxe.java_class(), "PickaxeItem");
        assert_eq!(ToolKind::Sword.java_class(), "SwordItem");
    }

    #[test]
    fn armor_slot_constants() {
        assert_eq!(ArmorSlot::Head.java(), "Type.HELMET");
        assert_eq!(ArmorSlot::Chest.name(), "chestplate");
    }

    #[test]
    fn tool_kind_from_str_round_trip() {
        for k in [
            ToolKind::Pickaxe,
            ToolKind::Axe,
            ToolKind::Shovel,
            ToolKind::Hoe,
            ToolKind::Sword,
        ] {
            assert_eq!(ToolKind::from_str(k.slug()).map(|v| v.slug()), Some(k.slug()));
        }
        assert!(ToolKind::from_str("hammer").is_none());
    }

    #[test]
    fn armor_slot_from_str_accepts_aliases() {
        assert!(matches!(ArmorSlot::from_str("helmet"), Some(ArmorSlot::Head)));
        assert!(matches!(ArmorSlot::from_str("BOOTS"), Some(ArmorSlot::Feet)));
        assert!(ArmorSlot::from_str("cape").is_none());
    }

    #[test]
    fn props_chain_skips_defaults() {
        let item = sample_item();
        // Default item: max_stack_size=64, rarity="common", no extras.
        // Should produce an empty chain.
        assert_eq!(build_item_props_chain(&item, &forge_1_20_4()), "");
    }

    #[test]
    fn props_chain_emits_stacks_and_rarity_and_fire_resistant() {
        let mut item = sample_item();
        item.max_stack_size = 16;
        item.rarity = "rare".into();
        item.is_fire_resistant = true;
        let chain = build_item_props_chain(&item, &forge_1_20_4());
        assert!(chain.contains(".stacksTo(16)"), "got: {chain}");
        assert!(chain.contains(".rarity(Rarity.RARE)"), "got: {chain}");
        assert!(chain.contains(".fireResistant()"), "got: {chain}");
    }

    #[test]
    fn props_chain_uses_max_count_on_fabric() {
        let mut item = sample_item();
        item.max_stack_size = 16;
        let chain = build_item_props_chain(&item, &fabric_1_20_4());
        assert!(chain.contains(".maxCount(16)"), "got: {chain}");
        assert!(!chain.contains(".stacksTo("), "Fabric should not use Forge name: {chain}");
    }

    #[test]
    fn props_chain_emits_durability_and_remainder() {
        let mut item = sample_item();
        item.durability = Some(250);
        item.recipe_remainder = Some("Items.BUCKET".into());
        let chain = build_item_props_chain(&item, &forge_1_20_4());
        assert!(chain.contains(".durability(250)"), "got: {chain}");
        assert!(chain.contains(".craftRemainder(Items.BUCKET)"), "got: {chain}");
    }

    #[test]
    fn props_chain_only_emits_attributes_marker_on_modern_profiles() {
        let mut item = sample_item();
        item.attribute_modifiers_json = Some(r#"[{"name":"speed","amount":0.1}]"#.into());

        let on_old = build_item_props_chain(&item, &forge_1_20_4());
        assert!(!on_old.contains("attributes("), "1.20.4 lacks .attributes(); got: {on_old}");

        let on_new = build_item_props_chain(&item, &neoforge_1_21());
        assert!(on_new.contains("attributes("), "1.21 should reference .attributes(); got: {on_new}");
    }
}
