//! Generic skeleton emitter for any FeatureKind that does not yet have a
//! full generator. The output is deliberately verbose — each file lists
//! the four capability dimensions (template / validator / deps /
//! version-aware) that still need to be implemented, and includes the
//! Minecraft / loader API surface the user will need to write against.
//!
//! The goal is **honest scaffolding**: instead of pretending the studio
//! can build a feature it cannot, we hand the user a clearly-marked TODO
//! file, a correct package, and a set of imports that compile against the
//! target loader. They can fill in the blanks; we get a structured place
//! to drop a real generator later.

use super::FeatureKind;
use crate::commands::codegen_commands::GeneratedFile;

fn capitalize(s: &str) -> String {
    let mut chars = s.chars();
    match chars.next() {
        None => String::new(),
        Some(c) => c.to_uppercase().collect::<String>() + chars.as_str(),
    }
}

fn to_pascal_case(s: &str) -> String {
    s.split(|c: char| !c.is_alphanumeric())
        .filter(|seg| !seg.is_empty())
        .map(capitalize)
        .collect()
}

fn java_package(namespace: &str, sub: &str) -> String {
    let base = if namespace.contains('.') {
        namespace.to_string()
    } else {
        format!("com.modstudio.{}", namespace)
    };
    if sub.is_empty() {
        base
    } else {
        format!("{}.{}", base, sub)
    }
}

/// Wrap a body in our standard skeleton header so every emitted file lists
/// the same checklist of what's missing.
fn skeleton_header(kind: FeatureKind, mc_version: &str, loader: &str) -> String {
    format!(
        "// =============================================================================\n\
         //  Generated by Minecraft Mod Studio — feature: {kind:?}\n\
         //\n\
         //  Status: SKELETON. The studio does not yet have a full generator for this\n\
         //  feature kind. The following capability dimensions are NOT YET satisfied:\n\
         //\n\
         //    [ ] template               (this file is a placeholder only)\n\
         //    [ ] validator              (no input rules are checked)\n\
         //    [ ] dependency resolver    (Gradle deps must be added by hand)\n\
         //    [ ] version-aware emitter  (output is hardcoded for {mc_version} on {loader})\n\
         //\n\
         //  Search for `TODO` below for the API surface you need to fill in.\n\
         // =============================================================================\n\n",
    )
}

/// Build a complete Java skeleton file for the given feature.
///
/// The returned `GeneratedFile.package_path` is relative to `src/main/java/`
/// so it can be written verbatim by the existing `write_generated_file`
/// command — the same path the Block / Item generators use.
pub fn emit_java_skeleton(
    kind: FeatureKind,
    namespace: &str,
    name: &str,
    loader: &str,
    mc_version: &str,
) -> GeneratedFile {
    let class_name = {
        let p = to_pascal_case(name);
        if p.is_empty() {
            format!("{:?}Skeleton", kind)
        } else {
            p
        }
    };

    let (sub_pkg, body) = match kind {
        FeatureKind::Tool => ("item", tool_body(&class_name, loader)),
        FeatureKind::Armor => ("item", armor_body(&class_name, loader)),
        FeatureKind::Food => ("item", food_body(&class_name, loader)),
        FeatureKind::Enchantment => ("enchantment", enchantment_body(&class_name, loader)),
        FeatureKind::Entity => ("entity", entity_body(&class_name, loader)),
        FeatureKind::GeckolibAnimation => ("entity", geckolib_body(&class_name, loader)),
        FeatureKind::Biome => ("world", biome_body(&class_name, loader)),
        FeatureKind::Dimension => ("world", dimension_body(&class_name, loader)),
        FeatureKind::WorldgenFeature => ("world", worldgen_body(&class_name, loader)),
        FeatureKind::Config => ("config", config_body(&class_name, loader)),
        FeatureKind::Keybind => ("client", keybind_body(&class_name, loader)),
        FeatureKind::Screen => ("client", screen_body(&class_name, loader)),
        FeatureKind::Command => ("command", command_body(&class_name, loader)),
        FeatureKind::Mixin => ("mixin", mixin_body(&class_name, loader)),
        FeatureKind::JeiIntegration => ("compat", jei_body(&class_name, loader)),
        // Items / Blocks / EventHandler / Recipe / Sound / Texture / Model /
        // LootTable / Advancement / DependencyIntegration are handled
        // elsewhere or are not Java-only — fall through to a generic stub.
        _ => ("misc", generic_body(&class_name, kind, loader)),
    };

    let pkg = java_package(namespace, sub_pkg);
    let header = skeleton_header(kind, mc_version, loader);
    let source = format!("{header}package {pkg};\n\n{body}\n");

    let package_path = pkg.replace('.', "/");
    GeneratedFile {
        file_name: format!("{class_name}.java"),
        package_path,
        source,
    }
}

/// Some features produce JSON or .gradle, not Java. The catalog hands back
/// whatever shape makes sense for the kind.
pub fn emit_non_java_skeleton(
    kind: FeatureKind,
    namespace: &str,
    name: &str,
    _loader: &str,
    _mc_version: &str,
) -> Option<GeneratedFile> {
    let modid = namespace.to_lowercase();
    match kind {
        FeatureKind::Recipe => Some(GeneratedFile {
            file_name: format!("{}.json", name.to_lowercase()),
            package_path: format!("../resources/data/{modid}/recipe"),
            source: r#"{
  "_comment": "TODO: recipe skeleton — fill in `type`, `pattern`, `key`, and `result`.",
  "type": "minecraft:crafting_shaped",
  "pattern": [
    "###",
    "# #",
    "###"
  ],
  "key": {
    "#": { "item": "minecraft:stone" }
  },
  "result": {
    "item": "minecraft:stone",
    "count": 1
  }
}
"#
            .into(),
        }),
        FeatureKind::LootTable => Some(GeneratedFile {
            file_name: format!("{}.json", name.to_lowercase()),
            package_path: format!("../resources/data/{modid}/loot_table/blocks"),
            source: r#"{
  "_comment": "TODO: replace with the actual block id and item drop.",
  "type": "minecraft:block",
  "pools": [
    {
      "rolls": 1,
      "entries": [
        { "type": "minecraft:item", "name": "minecraft:dirt" }
      ],
      "conditions": [
        { "condition": "minecraft:survives_explosion" }
      ]
    }
  ]
}
"#
            .into(),
        }),
        FeatureKind::Sound => Some(GeneratedFile {
            file_name: "sounds.json".into(),
            package_path: format!("../resources/assets/{modid}"),
            source: format!(
                "{{\n  \"{name}\": {{\n    \"category\": \"master\",\n    \"sounds\": [ \"{modid}:{name}\" ]\n  }}\n}}\n"
            ),
        }),
        FeatureKind::Model => Some(GeneratedFile {
            file_name: format!("{}.json", name.to_lowercase()),
            package_path: format!("../resources/assets/{modid}/models/block"),
            source: format!(
                "{{\n  \"parent\": \"minecraft:block/cube_all\",\n  \"textures\": {{\n    \"all\": \"{modid}:block/{name}\"\n  }}\n}}\n"
            ),
        }),
        FeatureKind::Texture => Some(GeneratedFile {
            file_name: format!("{name}.README.md"),
            package_path: format!("../resources/assets/{modid}/textures/block"),
            source: format!(
                "Drop a 16x16 PNG named `{name}.png` here.\n\n\
                 The studio cannot generate texture binaries yet — TODO: integrate an\n\
                 image-generation pipeline (e.g. asset-generator AI agent).\n"
            ),
        }),
        FeatureKind::DependencyIntegration => Some(GeneratedFile {
            file_name: "dependency.gradle.snippet".into(),
            package_path: ".".into(),
            source: format!(
                "// Append to build.gradle and adjust coordinates.\n\
                 //\n\
                 // TODO: replace `<group>:<artifact>:<version>` with the real\n\
                 // dependency you want to integrate.\n\n\
                 repositories {{\n\
                 \x20   maven {{ url 'https://maven.example.com' }}\n\
                 }}\n\n\
                 dependencies {{\n\
                 \x20   implementation '<group>:{name}:<version>'\n\
                 }}\n"
            ),
        }),
        _ => None,
    }
}

// ============================================================================
// Per-kind class bodies
// ============================================================================

fn tool_body(class_name: &str, _loader: &str) -> String {
    format!(
        "import net.minecraft.world.item.TieredItem;\n\
         import net.minecraft.world.item.Tier;\n\
         import net.minecraft.world.item.Item;\n\n\
         /**\n\
         \x20* {class_name} — pickaxe / axe / shovel / sword / hoe.\n\
         \x20*\n\
         \x20* TODO:\n\
         \x20*   1. Define a Tier (mining level, durability, attack damage).\n\
         \x20*   2. Subclass the appropriate vanilla tool (PickaxeItem, etc.).\n\
         \x20*   3. Add the tool tag (#minecraft:mineable/pickaxe …).\n\
         \x20*/\n\
         public final class {class_name} extends TieredItem {{\n\
         \x20   private {class_name}(Tier tier, Item.Properties props) {{\n\
         \x20       super(tier, props);\n\
         \x20   }}\n\
         }}\n",
    )
}

fn armor_body(class_name: &str, _loader: &str) -> String {
    format!(
        "import net.minecraft.world.item.ArmorItem;\n\
         import net.minecraft.world.item.ArmorMaterial;\n\
         import net.minecraft.world.item.Item;\n\n\
         /**\n\
         \x20* {class_name} — armor piece (helmet / chestplate / leggings / boots).\n\
         \x20*\n\
         \x20* TODO:\n\
         \x20*   1. Implement an ArmorMaterial (defence, toughness, equip sound).\n\
         \x20*   2. Register one ArmorItem per slot (HEAD/CHEST/LEGS/FEET).\n\
         \x20*   3. Provide armor texture at assets/<modid>/textures/models/armor/.\n\
         \x20*/\n\
         public final class {class_name} extends ArmorItem {{\n\
         \x20   public {class_name}(ArmorMaterial material, Type slot, Item.Properties props) {{\n\
         \x20       super(material, slot, props);\n\
         \x20   }}\n\
         }}\n",
    )
}

fn food_body(class_name: &str, _loader: &str) -> String {
    format!(
        "import net.minecraft.world.food.FoodProperties;\n\
         import net.minecraft.world.item.Item;\n\n\
         /**\n\
         \x20* {class_name} — edible item with nutrition and saturation.\n\
         \x20*\n\
         \x20* TODO:\n\
         \x20*   1. Tune nutrition / saturation values.\n\
         \x20*   2. Add MobEffectInstance entries for status effects.\n\
         \x20*   3. Mark `alwaysEat()` if appropriate.\n\
         \x20*/\n\
         public final class {class_name} {{\n\
         \x20   public static final FoodProperties FOOD = new FoodProperties.Builder()\n\
         \x20       .nutrition(4)\n\
         \x20       .saturationMod(0.3f)\n\
         \x20       .build();\n\n\
         \x20   public static Item.Properties properties() {{\n\
         \x20       return new Item.Properties().food(FOOD);\n\
         \x20   }}\n\n\
         \x20   private {class_name}() {{}}\n\
         }}\n",
    )
}

fn enchantment_body(class_name: &str, _loader: &str) -> String {
    format!(
        "import net.minecraft.world.entity.EquipmentSlot;\n\
         import net.minecraft.world.item.enchantment.Enchantment;\n\
         import net.minecraft.world.item.enchantment.EnchantmentCategory;\n\n\
         /**\n\
         \x20* {class_name} — custom enchantment.\n\
         \x20*\n\
         \x20* TODO:\n\
         \x20*   1. Pick the right EnchantmentCategory (WEAPON, ARMOR, …).\n\
         \x20*   2. Implement getMinCost / getMaxCost level curves.\n\
         \x20*   3. Override doPostAttack / doPostHurt for active effects.\n\
         \x20*/\n\
         public final class {class_name} extends Enchantment {{\n\
         \x20   public {class_name}() {{\n\
         \x20       super(Rarity.UNCOMMON, EnchantmentCategory.BREAKABLE, new EquipmentSlot[]{{ EquipmentSlot.MAINHAND }});\n\
         \x20   }}\n\n\
         \x20   @Override public int getMaxLevel() {{ return 3; }}\n\
         }}\n",
    )
}

fn entity_body(class_name: &str, _loader: &str) -> String {
    format!(
        "import net.minecraft.world.entity.Mob;\n\
         import net.minecraft.world.entity.EntityType;\n\
         import net.minecraft.world.level.Level;\n\
         import net.minecraft.world.entity.ai.attributes.AttributeSupplier;\n\
         import net.minecraft.world.entity.ai.attributes.Attributes;\n\n\
         /**\n\
         \x20* {class_name} — custom entity (mob / NPC / projectile).\n\
         \x20*\n\
         \x20* TODO:\n\
         \x20*   1. Register a SpawnEggItem and an entity type.\n\
         \x20*   2. Implement registerGoals() with AI tasks.\n\
         \x20*   3. Provide an EntityRenderer + Model on the client.\n\
         \x20*/\n\
         public final class {class_name} extends Mob {{\n\
         \x20   public {class_name}(EntityType<? extends Mob> type, Level level) {{\n\
         \x20       super(type, level);\n\
         \x20   }}\n\n\
         \x20   public static AttributeSupplier.Builder createAttributes() {{\n\
         \x20       return Mob.createMobAttributes()\n\
         \x20           .add(Attributes.MAX_HEALTH, 20.0)\n\
         \x20           .add(Attributes.MOVEMENT_SPEED, 0.3);\n\
         \x20   }}\n\
         }}\n",
    )
}

fn geckolib_body(class_name: &str, _loader: &str) -> String {
    format!(
        "// TODO: Add Geckolib to gradle.properties / build.gradle:\n\
         //     dependencies {{ implementation 'software.bernie.geckolib:geckolib-<loader>:<ver>' }}\n\n\
         import software.bernie.geckolib.animatable.GeoAnimatable;\n\
         import software.bernie.geckolib.core.animatable.instadc.AnimatableInstanceCache;\n\
         import software.bernie.geckolib.util.GeckoLibUtil;\n\
         import software.bernie.geckolib.core.animation.AnimatableManager;\n\n\
         /**\n\
         \x20* {class_name} — Geckolib animation controller.\n\
         \x20*\n\
         \x20* TODO:\n\
         \x20*   1. Add a .geo.json model under assets/<modid>/geo/.\n\
         \x20*   2. Add an .animation.json under assets/<modid>/animations/.\n\
         \x20*   3. Wire AnimationController predicates.\n\
         \x20*/\n\
         public final class {class_name} implements GeoAnimatable {{\n\
         \x20   private final AnimatableInstanceCache cache = GeckoLibUtil.createInstanceCache(this);\n\
         \x20   @Override public void registerControllers(AnimatableManager.ControllerRegistrar c) {{ /* TODO */ }}\n\
         \x20   @Override public AnimatableInstanceCache getAnimatableInstanceCache() {{ return cache; }}\n\
         \x20   @Override public double getTick(Object o) {{ return 0; }}\n\
         }}\n",
    )
}

fn biome_body(class_name: &str, _loader: &str) -> String {
    format!(
        "import net.minecraft.world.level.biome.Biome;\n\
         import net.minecraft.world.level.biome.BiomeGenerationSettings;\n\
         import net.minecraft.world.level.biome.MobSpawnSettings;\n\n\
         /**\n\
         \x20* {class_name} — custom biome definition.\n\
         \x20*\n\
         \x20* TODO:\n\
         \x20*   1. Provide a BiomeGenerationSettings (carvers, features, surface).\n\
         \x20*   2. Provide a MobSpawnSettings (creatures + ambient mobs).\n\
         \x20*   3. Register the biome via BootstapContext / DataPack.\n\
         \x20*/\n\
         public final class {class_name} {{\n\
         \x20   public static Biome create() {{\n\
         \x20       throw new UnsupportedOperationException(\"TODO: build {class_name} via Biome.BiomeBuilder\");\n\
         \x20   }}\n\
         \x20   private {class_name}() {{}}\n\
         }}\n",
    )
}

fn dimension_body(class_name: &str, _loader: &str) -> String {
    format!(
        "/**\n\
         \x20* {class_name} — custom dimension type + level stem.\n\
         \x20*\n\
         \x20* TODO:\n\
         \x20*   1. Add a dimension_type JSON under data/<modid>/dimension_type/.\n\
         \x20*   2. Add a dimension JSON under data/<modid>/dimension/.\n\
         \x20*   3. Reference a chunk generator (NoiseBased / Flat / Custom).\n\
         \x20*/\n\
         public final class {class_name} {{\n\
         \x20   public static final String DIMENSION_ID = \"{class_name}\";\n\
         \x20   private {class_name}() {{}}\n\
         }}\n",
    )
}

fn worldgen_body(class_name: &str, _loader: &str) -> String {
    format!(
        "/**\n\
         \x20* {class_name} — ConfiguredFeature + PlacedFeature pair.\n\
         \x20*\n\
         \x20* TODO:\n\
         \x20*   1. Add configured_feature JSON (data/<modid>/worldgen/configured_feature/).\n\
         \x20*   2. Add placed_feature JSON (data/<modid>/worldgen/placed_feature/).\n\
         \x20*   3. Reference the placed feature from a biome modifier.\n\
         \x20*/\n\
         public final class {class_name} {{\n\
         \x20   private {class_name}() {{}}\n\
         }}\n",
    )
}

fn config_body(class_name: &str, _loader: &str) -> String {
    format!(
        "import net.minecraftforge.common.ForgeConfigSpec;\n\n\
         /**\n\
         \x20* {class_name} — Forge ModConfig (Fabric: replace with @ConfigEntries).\n\
         \x20*\n\
         \x20* TODO:\n\
         \x20*   1. Add real config fields under SPEC.\n\
         \x20*   2. Register the spec in your @Mod constructor.\n\
         \x20*/\n\
         public final class {class_name} {{\n\
         \x20   public static final ForgeConfigSpec.Builder BUILDER = new ForgeConfigSpec.Builder();\n\
         \x20   public static final ForgeConfigSpec SPEC = BUILDER.build();\n\
         \x20   private {class_name}() {{}}\n\
         }}\n",
    )
}

fn keybind_body(class_name: &str, _loader: &str) -> String {
    format!(
        "import net.minecraft.client.KeyMapping;\n\
         import com.mojang.blaze3d.platform.InputConstants;\n\
         import org.lwjgl.glfw.GLFW;\n\n\
         /**\n\
         \x20* {class_name} — client-side keybind.\n\
         \x20*\n\
         \x20* TODO:\n\
         \x20*   1. Register via ClientRegistry.registerKeyBinding (Forge) or\n\
         \x20*      KeyBindingHelper.registerKeyBinding (Fabric).\n\
         \x20*   2. Poll `key.consumeClick()` in a client tick handler.\n\
         \x20*/\n\
         public final class {class_name} {{\n\
         \x20   public static final KeyMapping KEY = new KeyMapping(\n\
         \x20       \"key.modid.{class_name}\",\n\
         \x20       InputConstants.Type.KEYSYM,\n\
         \x20       GLFW.GLFW_KEY_K,\n\
         \x20       \"key.categories.misc\"\n\
         \x20   );\n\
         \x20   private {class_name}() {{}}\n\
         }}\n",
    )
}

fn screen_body(class_name: &str, _loader: &str) -> String {
    format!(
        "import net.minecraft.client.gui.GuiGraphics;\n\
         import net.minecraft.client.gui.screens.inventory.AbstractContainerScreen;\n\
         import net.minecraft.world.entity.player.Inventory;\n\
         import net.minecraft.network.chat.Component;\n\
         import net.minecraft.world.inventory.AbstractContainerMenu;\n\n\
         /**\n\
         \x20* {class_name} — GUI screen.\n\
         \x20*\n\
         \x20* TODO:\n\
         \x20*   1. Define a MenuType + AbstractContainerMenu subclass.\n\
         \x20*   2. Add a background texture (assets/<modid>/textures/gui/).\n\
         \x20*   3. Override renderBg / render for custom visuals.\n\
         \x20*/\n\
         public final class {class_name}<T extends AbstractContainerMenu> extends AbstractContainerScreen<T> {{\n\
         \x20   public {class_name}(T menu, Inventory inv, Component title) {{ super(menu, inv, title); }}\n\
         \x20   @Override protected void renderBg(GuiGraphics g, float p, int mx, int my) {{ /* TODO */ }}\n\
         }}\n",
    )
}

fn command_body(class_name: &str, _loader: &str) -> String {
    format!(
        "import com.mojang.brigadier.CommandDispatcher;\n\
         import net.minecraft.commands.CommandSourceStack;\n\
         import net.minecraft.commands.Commands;\n\n\
         /**\n\
         \x20* {class_name} — server-side command.\n\
         \x20*\n\
         \x20* TODO:\n\
         \x20*   1. Subscribe to RegisterCommandsEvent (Forge) or\n\
         \x20*      CommandRegistrationCallback.EVENT (Fabric).\n\
         \x20*   2. Add real arguments (StringArgumentType, IntegerArgumentType, …).\n\
         \x20*   3. Implement the executes(...) callback.\n\
         \x20*/\n\
         public final class {class_name} {{\n\
         \x20   public static void register(CommandDispatcher<CommandSourceStack> dispatcher) {{\n\
         \x20       dispatcher.register(\n\
         \x20           Commands.literal(\"{class_name}\")\n\
         \x20               .executes(ctx -> 1)\n\
         \x20       );\n\
         \x20   }}\n\
         \x20   private {class_name}() {{}}\n\
         }}\n",
    )
}

fn mixin_body(class_name: &str, _loader: &str) -> String {
    format!(
        "import org.spongepowered.asm.mixin.Mixin;\n\
         import org.spongepowered.asm.mixin.injection.At;\n\
         import org.spongepowered.asm.mixin.injection.Inject;\n\
         import org.spongepowered.asm.mixin.injection.callback.CallbackInfo;\n\n\
         /**\n\
         \x20* {class_name} — Mixin patch.\n\
         \x20*\n\
         \x20* TODO:\n\
         \x20*   1. Replace `Object.class` with the real target class.\n\
         \x20*   2. Add the class to your mixins.json `mixins` array.\n\
         \x20*   3. Choose @Inject / @Redirect / @ModifyVariable / @Overwrite.\n\
         \x20*/\n\
         @Mixin(Object.class)\n\
         public abstract class {class_name} {{\n\
         \x20   @Inject(method = \"toString\", at = @At(\"HEAD\"), cancellable = true)\n\
         \x20   private void onToString(CallbackInfoReturnable<String> cir) {{\n\
         \x20       // TODO: real injection\n\
         \x20   }}\n\
         }}\n",
    )
}

fn jei_body(class_name: &str, _loader: &str) -> String {
    format!(
        "// TODO: Add JEI to build.gradle:\n\
         //     compileOnly fg.deobf(\"mezz.jei:jei-<mc>-common-api:<ver>\")\n\n\
         import mezz.jei.api.IModPlugin;\n\
         import mezz.jei.api.JeiPlugin;\n\
         import mezz.jei.api.registration.IRecipeCategoryRegistration;\n\
         import net.minecraft.resources.ResourceLocation;\n\n\
         @JeiPlugin\n\
         public final class {class_name} implements IModPlugin {{\n\
         \x20   public static final ResourceLocation UID = new ResourceLocation(\"modid\", \"{class_name}\");\n\
         \x20   @Override public ResourceLocation getPluginUid() {{ return UID; }}\n\
         \x20   @Override public void registerCategories(IRecipeCategoryRegistration r) {{ /* TODO */ }}\n\
         }}\n",
    )
}

fn generic_body(class_name: &str, kind: FeatureKind, _loader: &str) -> String {
    format!(
        "/**\n\
         \x20* {class_name} — {kind:?} skeleton.\n\
         \x20*\n\
         \x20* This kind does not have a per-feature template yet. Treat this file\n\
         \x20* as a placeholder and replace it with the real implementation.\n\
         \x20*/\n\
         public final class {class_name} {{\n\
         \x20   private {class_name}() {{}}\n\
         }}\n",
    )
}
