/**
 * Visual Scripting v2 — Complete Node Library
 * 50+ node definitions across 6 categories
 */
import type { NodeDefinition } from './types';

export const triggerNodes: NodeDefinition[] = [
  { type: 'event_blockBreak', label: 'On Block Break', category: 'trigger', description: 'Fires when player breaks a block', keywords: ['break','destroy','mine'], inputs: [], outputs: [{ id:'exec',label:'',type:'exec',direction:'output' },{ id:'player',label:'Player',type:'player',direction:'output' },{ id:'block',label:'Block',type:'block',direction:'output' },{ id:'pos',label:'Position',type:'position',direction:'output' }] },
  { type: 'event_blockPlace', label: 'On Block Place', category: 'trigger', description: 'Fires when player places a block', keywords: ['place','put'], inputs: [], outputs: [{ id:'exec',label:'',type:'exec',direction:'output' },{ id:'player',label:'Player',type:'player',direction:'output' },{ id:'block',label:'Block',type:'block',direction:'output' },{ id:'pos',label:'Position',type:'position',direction:'output' }] },
  { type: 'event_playerJoin', label: 'On Player Join', category: 'trigger', description: 'Fires when player connects', keywords: ['join','connect','login'], inputs: [], outputs: [{ id:'exec',label:'',type:'exec',direction:'output' },{ id:'player',label:'Player',type:'player',direction:'output' }] },
  { type: 'event_entityDeath', label: 'On Entity Death', category: 'trigger', description: 'Fires when entity dies', keywords: ['death','kill'], inputs: [], outputs: [{ id:'exec',label:'',type:'exec',direction:'output' },{ id:'entity',label:'Entity',type:'entity',direction:'output' },{ id:'killer',label:'Killer',type:'entity',direction:'output' }] },
  { type: 'event_itemUse', label: 'On Item Use', category: 'trigger', description: 'Fires on right-click with item', keywords: ['use','interact'], inputs: [], outputs: [{ id:'exec',label:'',type:'exec',direction:'output' },{ id:'player',label:'Player',type:'player',direction:'output' },{ id:'item',label:'Item',type:'item',direction:'output' }] },
  { type: 'event_serverTick', label: 'On Server Tick', category: 'trigger', description: '20 times per second', keywords: ['tick','update'], inputs: [], outputs: [{ id:'exec',label:'',type:'exec',direction:'output' },{ id:'tickCount',label:'Tick',type:'integer',direction:'output' }] },
  { type: 'event_customTimer', label: 'Custom Timer', category: 'trigger', description: 'Fires every N ticks', keywords: ['timer','interval'], inputs: [{ id:'interval',label:'Interval',type:'integer',direction:'input',defaultValue:20 }], outputs: [{ id:'exec',label:'',type:'exec',direction:'output' }] },
  { type: 'event_redstone', label: 'On Redstone', category: 'trigger', description: 'Redstone power change', keywords: ['redstone','power'], inputs: [], outputs: [{ id:'exec',label:'',type:'exec',direction:'output' },{ id:'pos',label:'Position',type:'position',direction:'output' },{ id:'power',label:'Power',type:'integer',direction:'output' }] },
];

export const conditionNodes: NodeDefinition[] = [
  { type: 'branch', label: 'Branch (If)', category: 'condition', description: 'Conditional branching', keywords: ['if','branch','condition'], inputs: [{ id:'exec',label:'',type:'exec',direction:'input' },{ id:'condition',label:'Condition',type:'boolean',direction:'input' }], outputs: [{ id:'true',label:'True',type:'exec',direction:'output' },{ id:'false',label:'False',type:'exec',direction:'output' }] },
  { type: 'switch', label: 'Switch', category: 'condition', description: 'Multi-path branching', keywords: ['switch','case'], inputs: [{ id:'exec',label:'',type:'exec',direction:'input' },{ id:'value',label:'Value',type:'any',direction:'input' }], outputs: [{ id:'case0',label:'Case 0',type:'exec',direction:'output' },{ id:'case1',label:'Case 1',type:'exec',direction:'output' },{ id:'default',label:'Default',type:'exec',direction:'output' }] },
  { type: 'compare', label: 'Compare', category: 'condition', description: 'Compare two values', keywords: ['compare','equal','greater'], isPure: true, inputs: [{ id:'a',label:'A',type:'any',direction:'input' },{ id:'b',label:'B',type:'any',direction:'input' }], outputs: [{ id:'result',label:'Result',type:'boolean',direction:'output' }] },
  { type: 'and_gate', label: 'AND', category: 'condition', description: 'Boolean AND', isPure: true, isCompact: true, keywords: ['and','logic'], inputs: [{ id:'a',label:'A',type:'boolean',direction:'input' },{ id:'b',label:'B',type:'boolean',direction:'input' }], outputs: [{ id:'result',label:'',type:'boolean',direction:'output' }] },
  { type: 'or_gate', label: 'OR', category: 'condition', description: 'Boolean OR', isPure: true, isCompact: true, keywords: ['or','logic'], inputs: [{ id:'a',label:'A',type:'boolean',direction:'input' },{ id:'b',label:'B',type:'boolean',direction:'input' }], outputs: [{ id:'result',label:'',type:'boolean',direction:'output' }] },
  { type: 'not_gate', label: 'NOT', category: 'condition', description: 'Invert boolean', isPure: true, isCompact: true, keywords: ['not','invert'], inputs: [{ id:'input',label:'In',type:'boolean',direction:'input' }], outputs: [{ id:'result',label:'Out',type:'boolean',direction:'output' }] },
  { type: 'random_chance', label: 'Random Chance', category: 'condition', description: 'True with probability', isPure: true, keywords: ['random','chance'], inputs: [{ id:'chance',label:'%',type:'float',direction:'input',defaultValue:50 }], outputs: [{ id:'result',label:'',type:'boolean',direction:'output' }] },
  { type: 'has_item', label: 'Has Item?', category: 'condition', description: 'Check player inventory', isPure: true, keywords: ['has','item','inventory'], inputs: [{ id:'player',label:'Player',type:'player',direction:'input' },{ id:'item',label:'Item',type:'item',direction:'input' }], outputs: [{ id:'result',label:'Has?',type:'boolean',direction:'output' }] },
];

export const actionNodes: NodeDefinition[] = [
  { type: 'action_sendMessage', label: 'Send Message', category: 'action', description: 'Chat message to player', keywords: ['message','chat','send'], inputs: [{ id:'exec',label:'',type:'exec',direction:'input' },{ id:'player',label:'Player',type:'player',direction:'input' },{ id:'message',label:'Message',type:'string',direction:'input',defaultValue:'Hello!' }], outputs: [{ id:'exec',label:'',type:'exec',direction:'output' }] },
  { type: 'action_giveItem', label: 'Give Item', category: 'action', description: 'Add item to inventory', keywords: ['give','item','inventory'], inputs: [{ id:'exec',label:'',type:'exec',direction:'input' },{ id:'player',label:'Player',type:'player',direction:'input' },{ id:'item',label:'Item',type:'item',direction:'input' },{ id:'count',label:'Count',type:'integer',direction:'input',defaultValue:1 }], outputs: [{ id:'exec',label:'',type:'exec',direction:'output' }] },
  { type: 'action_setBlock', label: 'Set Block', category: 'action', description: 'Place block in world', keywords: ['set','block','place'], inputs: [{ id:'exec',label:'',type:'exec',direction:'input' },{ id:'pos',label:'Position',type:'position',direction:'input' },{ id:'block',label:'Block',type:'block',direction:'input' }], outputs: [{ id:'exec',label:'',type:'exec',direction:'output' }] },
  { type: 'action_spawnEntity', label: 'Spawn Entity', category: 'action', description: 'Spawn entity at position', keywords: ['spawn','entity','summon'], inputs: [{ id:'exec',label:'',type:'exec',direction:'input' },{ id:'pos',label:'Position',type:'position',direction:'input' },{ id:'entityType',label:'Type',type:'string',direction:'input',defaultValue:'zombie' }], outputs: [{ id:'exec',label:'',type:'exec',direction:'output' },{ id:'entity',label:'Spawned',type:'entity',direction:'output' }] },
  { type: 'action_teleport', label: 'Teleport', category: 'action', description: 'Move entity to position', keywords: ['teleport','tp','move'], inputs: [{ id:'exec',label:'',type:'exec',direction:'input' },{ id:'entity',label:'Entity',type:'entity',direction:'input' },{ id:'pos',label:'Target',type:'position',direction:'input' }], outputs: [{ id:'exec',label:'',type:'exec',direction:'output' }] },
  { type: 'action_playSound', label: 'Play Sound', category: 'action', description: 'Play sound effect', keywords: ['sound','audio','play'], inputs: [{ id:'exec',label:'',type:'exec',direction:'input' },{ id:'pos',label:'Position',type:'position',direction:'input' },{ id:'sound',label:'Sound',type:'string',direction:'input',defaultValue:'entity.experience_orb.pickup' }], outputs: [{ id:'exec',label:'',type:'exec',direction:'output' }] },
  { type: 'action_particle', label: 'Spawn Particles', category: 'action', description: 'Particle effects', keywords: ['particle','effect','fx'], inputs: [{ id:'exec',label:'',type:'exec',direction:'input' },{ id:'pos',label:'Position',type:'position',direction:'input' },{ id:'type',label:'Type',type:'string',direction:'input',defaultValue:'flame' },{ id:'count',label:'Count',type:'integer',direction:'input',defaultValue:10 }], outputs: [{ id:'exec',label:'',type:'exec',direction:'output' }] },
  { type: 'action_potion', label: 'Apply Potion', category: 'action', description: 'Give potion effect', keywords: ['potion','effect','buff'], inputs: [{ id:'exec',label:'',type:'exec',direction:'input' },{ id:'entity',label:'Entity',type:'entity',direction:'input' },{ id:'effect',label:'Effect',type:'string',direction:'input',defaultValue:'speed' },{ id:'duration',label:'Duration',type:'integer',direction:'input',defaultValue:200 }], outputs: [{ id:'exec',label:'',type:'exec',direction:'output' }] },
  { type: 'action_command', label: 'Execute Command', category: 'action', description: 'Run server command', keywords: ['command','cmd','execute'], inputs: [{ id:'exec',label:'',type:'exec',direction:'input' },{ id:'command',label:'Command',type:'string',direction:'input',defaultValue:'/say hello' }], outputs: [{ id:'exec',label:'',type:'exec',direction:'output' },{ id:'success',label:'OK?',type:'boolean',direction:'output' }] },
  { type: 'action_title', label: 'Show Title', category: 'action', description: 'Display title on screen', keywords: ['title','subtitle','display'], inputs: [{ id:'exec',label:'',type:'exec',direction:'input' },{ id:'player',label:'Player',type:'player',direction:'input' },{ id:'title',label:'Title',type:'string',direction:'input' },{ id:'subtitle',label:'Subtitle',type:'string',direction:'input' }], outputs: [{ id:'exec',label:'',type:'exec',direction:'output' }] },
];

export const flowNodes: NodeDefinition[] = [
  { type: 'flow_forLoop', label: 'For Loop', category: 'flow', description: 'Repeat N times', keywords: ['for','loop','repeat'], inputs: [{ id:'exec',label:'',type:'exec',direction:'input' },{ id:'start',label:'Start',type:'integer',direction:'input',defaultValue:0 },{ id:'end',label:'End',type:'integer',direction:'input',defaultValue:10 }], outputs: [{ id:'body',label:'Body',type:'exec',direction:'output' },{ id:'done',label:'Done',type:'exec',direction:'output' },{ id:'index',label:'i',type:'integer',direction:'output' }] },
  { type: 'flow_forEach', label: 'For Each', category: 'flow', description: 'Iterate array', keywords: ['foreach','each','iterate'], inputs: [{ id:'exec',label:'',type:'exec',direction:'input' },{ id:'array',label:'Array',type:'array',direction:'input' }], outputs: [{ id:'body',label:'Body',type:'exec',direction:'output' },{ id:'done',label:'Done',type:'exec',direction:'output' },{ id:'element',label:'Item',type:'any',direction:'output' }] },
  { type: 'flow_whileLoop', label: 'While Loop', category: 'flow', description: 'Repeat while true', keywords: ['while','loop'], inputs: [{ id:'exec',label:'',type:'exec',direction:'input' },{ id:'condition',label:'Condition',type:'boolean',direction:'input' }], outputs: [{ id:'body',label:'Body',type:'exec',direction:'output' },{ id:'done',label:'Done',type:'exec',direction:'output' }] },
  { type: 'flow_delay', label: 'Delay', category: 'flow', description: 'Wait N ticks', keywords: ['delay','wait','timer'], inputs: [{ id:'exec',label:'',type:'exec',direction:'input' },{ id:'ticks',label:'Ticks',type:'integer',direction:'input',defaultValue:20 }], outputs: [{ id:'exec',label:'',type:'exec',direction:'output' }] },
  { type: 'flow_sequence', label: 'Sequence', category: 'flow', description: 'Execute in order', keywords: ['sequence','order'], inputs: [{ id:'exec',label:'',type:'exec',direction:'input' }], outputs: [{ id:'out0',label:'Then 0',type:'exec',direction:'output' },{ id:'out1',label:'Then 1',type:'exec',direction:'output' },{ id:'out2',label:'Then 2',type:'exec',direction:'output' }] },
];

export const mathNodes: NodeDefinition[] = [
  { type: 'math_add', label: 'Add (+)', category: 'math', isPure: true, isCompact: true, description: 'A + B', keywords: ['add','plus','sum'], inputs: [{ id:'a',label:'A',type:'float',direction:'input',defaultValue:0 },{ id:'b',label:'B',type:'float',direction:'input',defaultValue:0 }], outputs: [{ id:'result',label:'=',type:'float',direction:'output' }] },
  { type: 'math_subtract', label: 'Subtract (-)', category: 'math', isPure: true, isCompact: true, description: 'A - B', keywords: ['subtract','minus'], inputs: [{ id:'a',label:'A',type:'float',direction:'input',defaultValue:0 },{ id:'b',label:'B',type:'float',direction:'input',defaultValue:0 }], outputs: [{ id:'result',label:'=',type:'float',direction:'output' }] },
  { type: 'math_multiply', label: 'Multiply (*)', category: 'math', isPure: true, isCompact: true, description: 'A * B', keywords: ['multiply','times'], inputs: [{ id:'a',label:'A',type:'float',direction:'input',defaultValue:0 },{ id:'b',label:'B',type:'float',direction:'input',defaultValue:1 }], outputs: [{ id:'result',label:'=',type:'float',direction:'output' }] },
  { type: 'math_divide', label: 'Divide (/)', category: 'math', isPure: true, isCompact: true, description: 'A / B', keywords: ['divide','division'], inputs: [{ id:'a',label:'A',type:'float',direction:'input',defaultValue:0 },{ id:'b',label:'B',type:'float',direction:'input',defaultValue:1 }], outputs: [{ id:'result',label:'=',type:'float',direction:'output' }] },
  { type: 'math_random', label: 'Random', category: 'math', isPure: true, description: 'Random in range', keywords: ['random','rand'], inputs: [{ id:'min',label:'Min',type:'float',direction:'input',defaultValue:0 },{ id:'max',label:'Max',type:'float',direction:'input',defaultValue:1 }], outputs: [{ id:'result',label:'Value',type:'float',direction:'output' }] },
  { type: 'math_clamp', label: 'Clamp', category: 'math', isPure: true, description: 'Constrain value', keywords: ['clamp','limit'], inputs: [{ id:'value',label:'Val',type:'float',direction:'input' },{ id:'min',label:'Min',type:'float',direction:'input',defaultValue:0 },{ id:'max',label:'Max',type:'float',direction:'input',defaultValue:1 }], outputs: [{ id:'result',label:'Out',type:'float',direction:'output' }] },
  { type: 'math_distance', label: 'Distance', category: 'math', isPure: true, description: 'Distance between positions', keywords: ['distance','range'], inputs: [{ id:'a',label:'A',type:'position',direction:'input' },{ id:'b',label:'B',type:'position',direction:'input' }], outputs: [{ id:'result',label:'Dist',type:'float',direction:'output' }] },
];

export const dataNodes: NodeDefinition[] = [
  { type: 'var_get', label: 'Get Variable', category: 'variable', isPure: true, description: 'Read variable', keywords: ['get','variable','read'], inputs: [], outputs: [{ id:'value',label:'Value',type:'any',direction:'output' }] },
  { type: 'var_set', label: 'Set Variable', category: 'variable', description: 'Write variable', keywords: ['set','variable','write'], inputs: [{ id:'exec',label:'',type:'exec',direction:'input' },{ id:'value',label:'Value',type:'any',direction:'input' }], outputs: [{ id:'exec',label:'',type:'exec',direction:'output' }] },
  { type: 'data_getString', label: 'String', category: 'data', isPure: true, isCompact: true, description: 'Text constant', keywords: ['string','text'], inputs: [{ id:'value',label:'',type:'string',direction:'input',defaultValue:'' }], outputs: [{ id:'out',label:'',type:'string',direction:'output' }] },
  { type: 'data_getInt', label: 'Integer', category: 'data', isPure: true, isCompact: true, description: 'Number constant', keywords: ['int','number'], inputs: [{ id:'value',label:'',type:'integer',direction:'input',defaultValue:0 }], outputs: [{ id:'out',label:'',type:'integer',direction:'output' }] },
  { type: 'data_concat', label: 'Concat', category: 'data', isPure: true, description: 'Join strings', keywords: ['concat','join','string'], inputs: [{ id:'a',label:'A',type:'string',direction:'input' },{ id:'b',label:'B',type:'string',direction:'input' }], outputs: [{ id:'result',label:'Text',type:'string',direction:'output' }] },
  { type: 'data_playerHealth', label: 'Get Health', category: 'data', isPure: true, description: 'Entity health', keywords: ['health','hp'], inputs: [{ id:'entity',label:'Entity',type:'entity',direction:'input' }], outputs: [{ id:'health',label:'HP',type:'float',direction:'output' },{ id:'maxHealth',label:'Max',type:'float',direction:'output' }] },
  { type: 'data_playerPos', label: 'Get Position', category: 'data', isPure: true, description: 'Entity position', keywords: ['position','pos','coords'], inputs: [{ id:'entity',label:'Entity',type:'entity',direction:'input' }], outputs: [{ id:'pos',label:'Pos',type:'position',direction:'output' },{ id:'x',label:'X',type:'float',direction:'output' },{ id:'y',label:'Y',type:'float',direction:'output' },{ id:'z',label:'Z',type:'float',direction:'output' }] },
];

export const ALL_NODES: NodeDefinition[] = [...triggerNodes, ...conditionNodes, ...actionNodes, ...flowNodes, ...mathNodes, ...dataNodes];

export const getNodeByType = (type: string) => ALL_NODES.find(n => n.type === type);

export const searchNodes = (query: string): NodeDefinition[] => {
  const q = query.toLowerCase();
  return ALL_NODES.filter(n => n.label.toLowerCase().includes(q) || n.description.toLowerCase().includes(q) || n.keywords?.some(k => k.includes(q)));
};
